### ISSUE TITLE
Update all dashboards to the Grafana BigQuery plugin

### ISSUE THREAD

**Issue by robertodauria** [m-lab/prometheus-support#1000]
After #999 the officially-supported BigQuery plugin and datasources are installed and can be used in dashboards. All the existing dashboards that run BQ queries should be ported to this new datasource before removing it.

**Comment by cristinaleonr** [comment]
TODO(@cristinaleonr): 

- [ ] Migrate Early-Exit dashboard to the latest Grafana BigQuery plugin.

**Comment by nkinkade** [comment]
I'm pretty sure this has been done. Closing.
