### ISSUE TITLE
We should collect metrics from the snmp-exporter itself

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#110]
http://snmp-exporter.sandbox.measurementlab.net:9116/metrics

**Comment by nkinkade** [comment]
@stephen-soltesz: This isn't exactly what you had in mind, I think, but I added two panels to the 'Switch Metrics' dashboard that display scrape times:

http://status-mlab-sandbox.measurementlab.net:3000/dashboard/db/switch-metrics?orgId=1

These are scrape times from the perspective of snmp_exporter, not Prom.

Are you wanting data on the VMs themselves, like memory and CPU usage? A lot of that data is probably already available in the default GCE graphs, but maybe we also want it in Grafana?

**Comment by stephen-soltesz** [comment]
All the data currently collected is using the snmp-exporter service. We are not yet monitoring the service itself. There should be a static rule to monitor http://snmp-exporter.{{PROJECT}}.measurementlab.net:9116/metrics -- this will allow us to use the metrics there as well as ultimately define alerts on when that service is missing.

When running in k8s services like that get monitored automatically. Since this is in GCE we need to add the target explicitly.

**Comment by nkinkade** [comment]
https://github.com/m-lab/prometheus-support/pull/111

**Comment by nkinkade** [comment]
Done:

https://github.com/m-lab/prometheus-support/pull/111
https://github.com/m-lab/prometheus-support/pull/112

[Example query](http://status-mlab-sandbox.measurementlab.net:9090/graph?g0.range_input=1h&g0.expr=up%7Bjob%3D%22snmp-exporter%22%7D&g0.tab=1)

@stephen-soltesz: Is this issue ready to close? I'm working on putting together an alert for the snmp_exporter instances, but that seems separate from this issue?

**Comment by stephen-soltesz** [comment]
How do we want to track releases to production? This is a general question that we should discuss in person.

**Comment by nkinkade** [comment]
We discussed this in the Ops Tactical call this morning. The plan, I believe, it to deploy to production on Mondays, whenever there are changes pending. How we actually track what needs deploying is an open question.

Is this issue resolved?

**Comment by stephen-soltesz** [comment]
I think so. Thank you!
