### ISSUE TITLE
Upgrade kube-state-metrics

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#160]
Later versions are now available (v1.1) which includes metrics like `kube_pod_container_status_terminated_reason` that would be super helpful for creating alerts to tell us when a container or pod crashes due to OOM or other unexpected issues.

https://github.com/kubernetes/kube-state-metrics

**Comment by pboothe** [comment]
This has ops implications, and Stephen will talk about it with them.

**Comment by stephen-soltesz** [comment]
Merging https://github.com/m-lab/prometheus-support/issues/49 with this issue.

For the production scraper config, kube-state-metrics is over-kill. It also exacerbates the issue of generating unnecessary time-series for new scraper deployments.

Also, many of the metrics it exports are not especially helpful for us.

The set of collector sets: https://github.com/kubernetes/kube-state-metrics/blob/master/main.go#L56

Metrics we definitely want:
```
kube_pod_container_status_restarts
kube_node_status_memory_pressure
kube_node_status_network_unavailable
kube_node_status_out_of_disk
kube_pod_status_phase
```

**Comment by stephen-soltesz** [comment]
Upgraded some time ago.
