### ISSUE TITLE
ParserDailyVolumeTooLow dashboard json should updated with improved alert.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/prometheus-support#179]
#167 fixes the ParserDailyVolumeTooLow alert, and #174 uses json imports to define dashboards.

We need to update the ParserDailyVolumeTooLow dashboard json to reflect the new alerting rule.
config/federation/grafana/dashboards/Alert_ParserDailyVolumeTooLow.json

**Comment by kokosta** [comment]
Done.

**Comment by kokosta** [comment]
Requires confirmation.

**Comment by stephen-soltesz** [comment]
Done.
