### ISSUE TITLE
Grafana Dashboards will exceed ConfigMap size limits

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#218]
Recently we encountered an issue where our deploy was failing due to:

```
The ConfigMap "grafana-dashboards" is invalid: metadata.annotations: Too long: must have at most 262144 characters
Script failed with status 1
```

It seems that every call to `kubectl apply` will store some metadata to assist with rollback. However, that metadata for the grafana dashboard data is too large.

To work around this we used `kubectl replace` which does not save that metadata. However ConfigMaps are still limited to 1MiB.  So, that change only buys us some time to find a better solution.

For some upstream discussion about this see, and the associated issues: https://github.com/kubernetes/kubernetes/issues/15878#issuecomment-149724570

**Comment by nkinkade** [comment]
This issue is coming to a head again. A prometheus-federation deployment just failed with this same error, despite using `kubectl replace`. I was able to get around the issue by modifying my PR slightly, but it means we are very close to the 1MB hard limit now. I suspect that the next dashboard that gets created will hit this limit and not be able to work around it.

**Comment by nkinkade** [comment]
Removed `P3` and `backlog` labels and readded `review/triage` so that this comes back up for consideration at the next Review Triage meeting in a week or so.

**Comment by stephen-soltesz** [comment]
If we can't use the configmap, could we use some variation of `rsync`'s `--delete` option to sync HEAD to grafana's local volume?

```
rsync -avh source/ dest/ --delete
```

**Comment by pboothe** [comment]
Mitigated for many months in the linked PR.

**Comment by nkinkade** [comment]
The mitigation in #440 reduced the size of dashboards by around 40%:

```
$ du -sh config/federation/grafana/dashboards
1.1M    config/federation/grafana/dashboards
$ du -sh config/federation/grafana/dashboards-minified
684K    config/federation/grafana/dashboards-minified
```
I suspect this will avoid this issue for another 6-12 months. However, we will run into this issue again.
