### ISSUE TITLE
LameDuckMetricMissingForNode should preserve machine labels

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#227]
Currently when alert LameDuckMetricMissingForNode fires it includes no label inormation. Without this information it is impossible to know the originating node with the problem or to silence the alert for specific nodes.

**Comment by nkinkade** [comment]
It's not impossible to know, but just more tedious than it needs to be. You can manually run the query that triggers the alert:

`up{service="nodeexporter"} == 1 UNLESS ON(machine) lame_duck_node{}`

I'll work on getting some label information in there to make this easier to discover from the alert itself.

**Comment by kokosta** [comment]
Done by nkinkade@
