### ISSUE TITLE
Second blackbox exporter on standby

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#245]
The global ndt rate reduction on 2018-06-12 was caused by an outage in the blackbox exporter.

If possible, we should run multiple instances on separate nodes, such that prometheus always uses one that is online.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/prometheus-support/pull/248 -- running in staging.

**Comment by pboothe** [comment]
Done
