### ISSUE TITLE
Improve worldmap bigquery exporter metrics

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#268]
In addition to removing the aliasing caused by 'group by machine', it should also be possible to simplify the worldmap setup by adding geohash labels directly to metrics.
https://github.com/m-lab/prometheus-support/pull/267

It should be possible to use BQ UDF to calculate an N-digit geohash from lat/lon. While prometheus will faithfully ingest any number, these are not without cost the larger they get, so we should use care about the number of distinct geohash values we calculate.

Approximate number of distinct position values based on geohash precision https://bigquery.cloud.google.com/savedquery/581276032543:c2ce630cc0b6412eba781ee316e60c59:
* 2 geohash digits - 196 values
* 3 geohash digits - 1220 values
* 4 geohash digits - 6729 values
* 5 geohash digits - 14459 values

The current queries return about 519 values. 3-digits should probably work. 4-digits would probably press the limits for the world map. Higher resolution than 4 should imply smaller regions.

**Comment by pboothe** [comment]
Done
