### ISSUE TITLE
Stable outbound IP needed for snmp-exporter

### ISSUE THREAD

**Issue by jheretic** [m-lab/prometheus-support#308]
Currently snmp-exporter is runs in its own GCE instance so that it can have a static outbound IP in order to ensure the ability to whitelist it on the switches. We want to move snmp-exporter back under GKE but still allow IP whitelisting. There are two ways to approach this:

- Using a NAT gateway. This will definitely work, but is complicated to setup and maintain.
- Ensure one or more static IPs are always assigned to one or more nodes, and then make sure that snmp-exporter is always scheduled on only those node(s).

Currently testing the second approach.

**Comment by stephen-soltesz** [comment]
@jheretic my understanding of our last conversation was that the second approach was preferable for the simplicity. This issue was updated very recently -- are you still exploring the first option?

**Comment by nkinkade** [comment]
This is done. Closing.
