### ISSUE TITLE
Prometheus 2.x web lifecycle hook times out

### ISSUE THREAD

**Issue by jheretic** [m-lab/prometheus-support#317]
The `/-/reload` URL that prompts Prometheus to reload its configuration files times out with a `504` error when called via the public URL. This doesn't seem to affect the configuration files actually being reloaded, and does not timeout when called via the private network (meaning it's probably a timeout of the public ingress), but it would probably be a good idea to change the configmap-reload configuration so that it doesn't call through the public ingress so that errors don't show up in its log.

**Comment by jheretic** [comment]
Furthermore, this causes Travis to hang when the `apply-cluster.sh` script runs and tries to hit the reload hook. We should look at how to fix and/or update that process as well, if it is even still necessary with the addition of configmap-reload.

**Comment by stephen-soltesz** [comment]
This may work for prometheus-federation also: https://github.com/m-lab/prometheus-support/blob/master/k8s/data-processing-cluster/deployments/prometheus.yml#L94

**Comment by nkinkade** [comment]
PR #328 should fix this. Closing.
