### ISSUE TITLE
Deploy kubeip to staging & oti and snmp exporter to GKE

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#366]
The changes in https://github.com/m-lab/prometheus-support/pull/362 makes it possible to run the SNMP exporter (and services that require static IPs) to run from a GKE node.

Preparatory steps are needed to smoothly deploy to staging and oti projects.

* *Allocate static IPs*
  
  The kubeip mechanism assigns -- use the instructions in https://github.com/m-lab/prometheus-support/pull/362 for allocating static IPs with the correct labels and values for kubeip.

* *Update and apply the QFX switch configuration to include new static IPs*
  
  Since we restrict SNMP access to specific IP sources, once we allocate new static IPs in GCP console, we must add them to the switch configuration.

* *Merge https://github.com/m-lab/prometheus-support/pull/362 and deploy (first to staging)*

* *Turn down SNMP exporter GCE VM*
  
  Once the snmp-exporter is running in GKE, confirmed to have access to the switches SNMP service, and auto-discovered by prometheus, the GCE VMs that currently host the snmp-exporters can be decommissioned. The PR above includes changes to the prometheus config to remove the static config for the VMs.

* *Repeat for mlab-oti*
  
  Ideally, the switch configuration update would occur only once. Just allocate the static IPs from both stating & oti at once.

**Comment by evfirerob** [comment]
With the release https://github.com/m-lab/prometheus-support/releases/tag/production%2F2.4 this has been deployed to mlab-oti. However, the service is failing because there aren't enough resources available on the node pool and autoscaling is off.

**Comment by evfirerob** [comment]
The snmp-exporter pods have been running since yesterday:
```
snmp-exporter-569564dfdc-f89sn          3/3       Running   0          18h
snmp-exporter-569564dfdc-lkl2n          3/3       Running   0          19h
```

The nodes have received the correct IPs:
```
gke-prometheus-feder-static-outbound--48f9d54d-hfnz   Ready     <none>    18h       v1.9.7-gke.11   35.188.150.110   Container-Optimized OS from Google   4.4.111+         docker://17.3.2
gke-prometheus-feder-static-outbound--48f9d54d-q9df   Ready     <none>    19h       v1.9.7-gke.11   35.202.153.90    Container-Optimized OS from Google   4.4.111+         docker://17.3.2
```
