### ISSUE TITLE
snmp-exporter needs a simple GCS config downloader

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#414]
The current strategy is hacky and apparently doesn't work right.

**Comment by nkinkade** [comment]
There was a situation on 2019-03-01 where updates to switch configs for TRN01 and ATL07 did not update automatically, and so Prometheus thought scraping was down at those sites. 

Inspecting the situation, it was clear that the new snmp_exporter config had been loaded into the containers, but for some reason snmp_exporter had not loaded this new config. This is _supposed_ to be the job of the configmap-reload sidecar container, but for some reason that was failing and that container had no logs. 

The workaround was to login to the service-discovery sidecar container and manually run:

`# curl http://localhost:9116/-/reload`

... which the configmap-reloader is supposed to do.

**Comment by stephen-soltesz** [comment]
@nkinkade https://github.com/m-lab/gcs-downloader

**Comment by nkinkade** [comment]
I update the snmp_exporter deployment to use this next weeks. Thanks!

**Comment by stephen-soltesz** [comment]
@nkinkade what is the status of this? It looks like the gsutil solution is still in HEAD -- https://github.com/m-lab/prometheus-support/blob/master/k8s/prometheus-federation/deployments/snmp-exporter.yml

**Comment by nkinkade** [comment]
@stephen-soltesz: https://github.com/m-lab/prometheus-support/pull/459

**Comment by stephen-soltesz** [comment]
:+1: thank you -- I think there was just confusion about this card on the favro board and it got marked as done before it was done.

**Comment by stephen-soltesz** [comment]
Or, maybe this was counting the time to write it and deploy it... that could be.
