### ISSUE TITLE
Move script_exporter from a GCE VM to GKE with static outbound IP

### ISSUE THREAD

**Issue by robertodauria** [m-lab/prometheus-support#494]
I believe we [thought of doing this for a long time](https://github.com/m-lab/prometheus-support/issues/308) and the blocker was that we didn't know how to assign a stable outbound IP to GKE pods at the time.

**Comment by nkinkade** [comment]
snmp_exporter is already in GKE. Do you mean script_exporter?

**Comment by robertodauria** [comment]
Definitely. Thanks.
