### ISSUE TITLE
bqx: replace bq_ndt_annotation metrics with ndt5 data

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#564]
The bigquery-exporter used to calculate the number of successfully geo & asn annotated NDT tests per day. We have alerts that depend on these metrics. It should be updated for tcpinfo, traceroute, and ndt5 data.

https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_ndt_annotation.sql

**Comment by mehtab11** [comment]
Closing this as obsolete.

**Comment by gfr10598** [comment]
m-lab/dev-tracker#507
