### ISSUE TITLE
bqx: update bq_gardener_parse_time tracking for canonical datatypes

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#565]
Currently, bigquery-exporter tracks the parse-time cycles for web100 datatypes. As we complete the migration to k8s this should monitor all datat types. We have alerts that depend on this.

Complete: https://github.com/m-lab/prometheus-support/pull/486

https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_gardener_parse_time.sql.template

**Comment by gfr10598** [comment]
m-lab/dev-tracker#507

**Comment by mehtab11** [comment]
Completed.
