### ISSUE TITLE
After a few days, prometheus starts losing samples on collection

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#58]
After a restart, prometheus 1.6.2 seems to handle the scraper-cluster data collection without issue. After about three days RAM usage grows steadily and begins to clip some collections.

![prom-samples](https://user-images.githubusercontent.com/1085316/27501327-a8b5cf60-583a-11e7-91e5-980156a367e0.png)

Those lines should be steady and straight.

I suspect the currently configured target-heap-size is too large. So, I'd like to try reducing the storage.local.target-heap-size flag

**Comment by robertodauria** [comment]
@stephen-soltesz is this still true?

**Comment by stephen-soltesz** [comment]
I don't think so -- iirc, that was a function of the older 1.x versions. I don't remember seeing this for a long time. A different current issue is history retention throughout the various deployments. Closing this issue.
