### ISSUE TITLE
Add "node status" summary to K8S: Workload dashboard

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#605]
When something is wrong with a cluster or node or pod, often a sensitive indication of that is the node status. In aggregate, the number of "false" or "unknown" status nodes can indicate a problem.

```
sum by(status) (kube_node_status_condition{condition="Ready", node=~".*"})
```

**Comment by nkinkade** [comment]
This is resolved by #612 which was merged. Closing.
