### ISSUE TITLE
alert: too many k8s or kernel versions

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#619]
One of the root causes of the pusher/TSO outage is that we had no monitoring on the heterogenous set of k8s and kernel versions running on the platform.

At steady state we should have 1. During a rollout we should have 2. That should not last more than a week. If the counts do not change within 24hr, then the rollout has stalled.

**Comment by nkinkade** [comment]
I believe this issue was resolved by PR #628. Closing.
