### ISSUE TITLE
Detect zombie nodes

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#620]
While evaluating the gcs-exporter, I found that mlab4.atl08 and mlab4.arn02 were still uploading tcpinfo data from the bismark experiment, even though the bismark experiment was no longer deployed to the staging k8s master and these nodes were unknown to the k8s master.

We should have monitoring that reconciles "inventory" with "running systems". i.e. hosts listed in a targets file with auto discovered nodes from k8s.

**Comment by nkinkade** [comment]
I believe this issue is resolved by PR #620, which was just merged. Closing. @stephen-soltesz, if you disagree because you feel PR #620 was faulty, please reopen.
