### ISSUE TITLE
cleanup: legacy-targets (0/1167 up)

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#674]
There are a large number of legacy targets (now all down) that should be removed from the prometheus configuration.

**Comment by stephen-soltesz** [comment]
mirror-node-exporter (0/1 up)

**Comment by stephen-soltesz** [comment]
blackbox-targets job for service="rsyncd" for ndt, neubot, and npad, mlab-utility ~1600 targets.

**Comment by nkinkade** [comment]
This was partially resolved by #678, but most of the issue was old legacy target files hanging around on the Prometheus persistent disk, which I have manually removed.
