### ISSUE TITLE
Investigate probing SSH on nodes through the flannel network

### ISSUE THREAD

**Issue by nkinkade** [m-lab/prometheus-support#696]
Since the M-Lab GCP projects were moved out of the google.com domain and into the measurementlab.net domain, we have been getting message from GCP like:

> Action required: Critical problem with your Google Cloud Platform / API project M-Lab Production (id: mlab-oti) IP 34.66.156.132, 35.238.48.112
>
> We've detected that your Google Cloud Project M-Lab Production (id: mlab-oti) IP 34.66.156.132, 35.238.48.112 appears to be performing intrusion attempts against a third party.

We keep appealing them, and they keep "reinstating" the service, only for the same alert to be send to us a few days later. Apparently these warnings are the result of Prometheus using blackbox_exporter to probe ports 22 and 830 on nodes, DRACs and switches.

We may not be able to currently do much about the DRAC and switch probes, but we might be able to tunnel the node SSH checks through the flannel overlay network.

**Comment by nkinkade** [comment]
@stephen-soltesz: based on our conversation in the staff call today, my takeaway was that we are not going to pursue the point in this issue. If this is correct, would you let me know, or else just close this issue?

**Comment by stephen-soltesz** [comment]
Next steps are ambiguous because we haven't identified the requirements yet. Since this is a specific strategy we can't be sure that it will address the unidentified requirements we'll discover in the future. I think it's fine to close this for now and once we know what we need revisit then.
