### ISSUE TITLE
Update alert to use ndt7 - DataQuality_TooManyNdtS2cTestsWithDiscards

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#749]
The bq_ndt_s2c query was originally written to support ndt5.

It should be updated to use (or include) ndt7, which now receives the majority of our measurements.

https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_ndt_s2c.sql

**Comment by nkinkade** [comment]
Using the `measurement-lab.ndt.unified_downloads` table is one possible solution. The only field missing test end time. Adding a new field to the unified table like `a.Duration` would make it complete. Adding that field, or a similar one, may actually become essential if/when we ever implement NDT7 early-exit.

**Comment by nkinkade** [comment]
We may be able to use the `unified_downloads` view in the not-distant future, but currently the view does not have any sort of test end time field or duration. In the meantime, to work around this somewhat serious defect/bug in the query, I will modify the query to somehow include both ndt5 and ndt7 S2C tests (probably some sort of UNION).
