### ISSUE TITLE
monitor system boot time with node-exporter

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#91]
This will allow us to monitor reboot rates and alert on higher-than-expected daily rates.

During the Oct3rd delete logs safely load incident, the reboot rate increased 2x, but we did not observe this until after the fact.

Incredibly, it doesn't appear that the node exporter supports reporting the value in `/proc/uptime` but if a file was written once on boot to the node exporter textfile directory then the `last boot time` could be collected by prometheus.

Or, we could create a super simple exporter.

**Comment by pboothe** [comment]
It looks like the metrics `node_boot_time` and `node_boot_time_seconds` are now available?

**Comment by nkinkade** [comment]
@pboothe: Is the `boottime` collector available for Linux? The [README file seems to mention](https://github.com/prometheus/node_exporter/#collectors) that it is only available for "Darwin, Dragonfly, FreeBSD, NetBSD, OpenBSD".

**Comment by nekketsuuu** [comment]
On Linux, you can use `node_boot_time_seconds` prepared by `stat` collector.

https://github.com/prometheus/node_exporter/blob/d8a1585f59ef1169837d08979ecc92dcea8aa58a/collector/stat_linux.go#L64-L68

https://github.com/prometheus/procfs/blob/ead9b6c0001eebe57bfa98615ee4cae0b7472c35/stat.go#L60-L61

If you want uptime, write:

```
time() - node_boot_time_seconds
```

**Comment by HiranChaudhuri** [comment]
> If you want uptime, write:
> 
> ```
> time() - node_boot_time_seconds
> ```

This has an interesting effect on desktop systems that suspend/hibernate. The number really shows how long the system has not been booted, not really how long the system was up. But I like it.

**Comment by nkinkade** [comment]
@stephen-soltesz: The recent comments to this issue brought it to my attention. As far as I know, this issue was resolved a long time ago (we are collecting and calculating uptime), but the issue got lost in the mix. Will you please close this issue if you agree, else elaborate on what else needs to be done?

**Comment by stephen-soltesz** [comment]
@nkinkade I think you're right.

**Comment by yarix** [comment]
with grafana one can do:
```node_boot_time_seconds{instance=~"$v_instance"}*1000``` and set the unit to Date & time / From now.

![image](https://user-images.githubusercontent.com/6409857/163848226-69e941e5-f8c1-439e-8e77-03016642da66.png)
