### ISSUE TITLE
Install officially maintained bigquery datasource plugin

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#986]
The bigquery datasource installed in M-Lab's Grafana instances is now unsupported, as of 2022 - https://github.com/doitintl/bigquery-grafana

The new bigquery datasource plugin is now officially maintained by grafana  - https://github.com/grafana/google-bigquery-datasource

We should upgrade this version.

Note: It is possible that the new version supports Grafana variable substitutions and dependency tracking (whereas the old version appears not to) (e.g. one variable uses a second variable in a query).

**Comment by robertodauria** [comment]
https://github.com/m-lab/prometheus-support/issues/1000
